[package]

name = "rcc"
version = "0.0.1"
authors = ["John Hodge <tpg@mutabah.net>"]

[dependencies]
log = "0.4"
env_logger = "0.5"
structopt = "0.2"
utf8reader = "*"

cranelift-frontend = "0.58"
cranelift-codegen = "0.58"
cranelift-module = "0.58"
cranelift-object = "0.58"
target-lexicon = "*"
